---
ID: "47b28cfb-18e2-401b-9fe0-1a5cc79f273d"
Parent: "3fc26e85-2912-4933-afd1-a4fce6fd46c8"
Template: "3fc26e85-2912-4933-afd1-a4fce6fd46c8"
Path: /sitecore/templates/Feature/JSS Experience Accelerator/BasicSiteA/BlogsFolder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{AA1A087C-18E2-4B5B-813C-DE646B0C7346}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230516T061538Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0c22d492-bff9-403b-a7b6-1ee32a8c22b9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230516T061756Z
