---
ID: "5f873547-6041-44ec-b239-c002471cf5bb"
Parent: "4243046a-2e9e-4e67-8c9a-36df2a23a1c2"
Template: "1105b8f8-1e00-426b-bf1f-c840742d827b"
Path: /sitecore/content/BasicSiteA/BasicSiteA/Presentation/Page Designs/Default
SharedFields:
- ID: "0966b999-0d0e-4278-acc9-9da69d461fe6"
  Hint: PartialDesigns
  Value: "{F22223EF-4164-4D0C-A97B-50B0FCDAFA3B}|{7EDEF02E-66DF-4809-86EE-B60AFFAD8DF9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230511T072624Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c5729a0b-c223-427d-b5b5-e25f81af009d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230511T072629Z
